# Generated by Django 3.2.4 on 2021-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=26)),
                ('pass2', models.CharField(max_length=26)),
            ],
        ),
    ]
